export type DayActivity = {
  time: string;
  activity: string;
  emoji: string;
};

export type Career = {
  id: string;
  title: string;
  area: string;
  emoji: string;
  color: string;
  lightBg: string;
  description: string;
  salary: string;
  salaryMin: number;
  skills: string[];
  dayInLife: DayActivity[];
  universities: string[];
  outlook: "Alta" | "Media" | "Estable";
  duration: string;
  nowDoing: string;
  scene: string[];
  tools: string[];
};

export const AREAS = [
  "Todos",
  "Tecnología",
  "Salud",
  "Derecho",
  "Negocios",
  "Diseño",
  "Ingeniería",
  "Educación",
  "Ciencias",
  "Gastronomía",
  "Humanidades",
];

export const careers: Career[] = [
  {
    id: "software",
    title: "Ingeniería de Software",
    area: "Tecnología",
    emoji: "💻",
    color: "#dc2626",
    lightBg: "#fff1f1",
    description:
      "Diseñas y construyes el software que mueve al mundo. Desde apps móviles hasta sistemas bancarios, tu código resuelve problemas reales.",
    salary: "S/. 4,000 – 15,000",
    salaryMin: 4000,
    skills: ["Programación", "Lógica", "Trabajo en equipo", "Aprendizaje continuo", "Resolución de problemas"],
    dayInLife: [
      { time: "9:00 am", activity: "Daily standup con tu equipo (15 min)", emoji: "🤝" },
      { time: "9:30 am", activity: "Revisas el tablero de tareas y priorizas", emoji: "📋" },
      { time: "10:00 am", activity: "Programas una nueva funcionalidad", emoji: "⌨️" },
      { time: "1:00 pm", activity: "Almuerzo y scrolleas GitHub trends", emoji: "🍱" },
      { time: "2:00 pm", activity: "Code review del pull request de un colega", emoji: "🔍" },
      { time: "3:30 pm", activity: "Corriges bugs reportados en producción", emoji: "🐛" },
      { time: "5:00 pm", activity: "Deploy a staging y documentas cambios", emoji: "🚀" },
    ],
    universities: ["PUCP", "UNI", "UTEC", "U. Lima", "UPC", "UNMSM"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "Escribiendo código en tu IDE favorito, probablemente VS Code con música lo-fi de fondo.",
    scene: ["💻", "⌨️", "🖥️", "☕", "🎧"],
    tools: ["React", "Python", "AWS", "Docker", "Git"],
  },
  {
    id: "medicina",
    title: "Medicina Humana",
    area: "Salud",
    emoji: "🩺",
    color: "#059669",
    lightBg: "#f0fdf4",
    description:
      "Salvas vidas. Diagnósticas, tratas y acompañas a personas en sus momentos más vulnerables. Es la carrera más demandante y más humana.",
    salary: "S/. 5,000 – 18,000",
    salaryMin: 5000,
    skills: ["Empatía", "Precisión", "Resistencia", "Toma de decisiones", "Memorización"],
    dayInLife: [
      { time: "7:00 am", activity: "Visita matutina a pacientes hospitalizados", emoji: "🏥" },
      { time: "9:00 am", activity: "Consultas en consultorio externo", emoji: "👨‍⚕️" },
      { time: "12:00 pm", activity: "Revisión de resultados de laboratorio", emoji: "🔬" },
      { time: "1:00 pm", activity: "Almuerzo rápido entre turnos", emoji: "🍽️" },
      { time: "2:00 pm", activity: "Procedimientos o cirugías programadas", emoji: "🏨" },
      { time: "4:00 pm", activity: "Actualización de historias clínicas", emoji: "📝" },
      { time: "6:00 pm", activity: "Interconsultas con especialistas", emoji: "📞" },
    ],
    universities: ["UNMSM", "UPCH (Cayetano)", "PUCP", "U. Lima", "UCSUR", "URP"],
    outlook: "Alta",
    duration: "7 años + especialidad",
    nowDoing: "Atendiendo a un paciente en consultorio o revisando resultados de exámenes.",
    scene: ["🏥", "🩺", "💊", "🔬", "🩻"],
    tools: ["Estetoscopio", "RX Digital", "Historia clínica", "Ecógrafo"],
  },
  {
    id: "derecho",
    title: "Derecho",
    area: "Derecho",
    emoji: "⚖️",
    color: "#b45309",
    lightBg: "#fffbeb",
    description:
      "Defiendes derechos, argumentas casos y das forma a la justicia. El derecho está en todo: empresas, familias, el Estado y la sociedad.",
    salary: "S/. 3,000 – 12,000",
    salaryMin: 3000,
    skills: ["Argumentación", "Lectura crítica", "Negociación", "Ética", "Escritura"],
    dayInLife: [
      { time: "8:00 am", activity: "Revisas expedientes y jurisprudencia", emoji: "📚" },
      { time: "9:30 am", activity: "Reunión con cliente para estrategia legal", emoji: "🤝" },
      { time: "11:00 am", activity: "Redactas escritos, demandas o contratos", emoji: "✍️" },
      { time: "1:00 pm", activity: "Almuerzo y repaso de audios de audiencias", emoji: "🍱" },
      { time: "2:30 pm", activity: "Audiencia o diligencia en juzgado", emoji: "🏛️" },
      { time: "4:00 pm", activity: "Revisión de contratos para empresa cliente", emoji: "📄" },
      { time: "6:00 pm", activity: "Investigación jurídica para el caso del día siguiente", emoji: "🔍" },
    ],
    universities: ["PUCP", "UNMSM", "U. Lima", "UPC", "UP", "USMP"],
    outlook: "Media",
    duration: "5 años",
    nowDoing: "Redactando un escrito judicial o revisando contratos en tu computadora.",
    scene: ["⚖️", "📚", "🏛️", "📄", "🔍"],
    tools: ["El Peruano", "SREJ", "LexisNexis", "Word"],
  },
  {
    id: "administracion",
    title: "Administración de Empresas",
    area: "Negocios",
    emoji: "📊",
    color: "#7c3aed",
    lightBg: "#f5f3ff",
    description:
      "Líderas organizaciones, tomas decisiones estratégicas y haces que los equipos y recursos funcionen al máximo. La carrera más versátil del mundo de negocios.",
    salary: "S/. 3,000 – 12,000",
    salaryMin: 3000,
    skills: ["Liderazgo", "Pensamiento estratégico", "Comunicación", "Análisis financiero", "Gestión de equipos"],
    dayInLife: [
      { time: "8:30 am", activity: "Revisas KPIs y dashboard del negocio", emoji: "📈" },
      { time: "9:00 am", activity: "Reunión de alineación con el equipo gerencial", emoji: "🗣️" },
      { time: "10:30 am", activity: "Análisis de propuesta de nuevo proveedor", emoji: "🤝" },
      { time: "1:00 pm", activity: "Almuerzo de trabajo con cliente clave", emoji: "🍽️" },
      { time: "2:30 pm", activity: "Presentación de resultados al directorio", emoji: "📊" },
      { time: "4:00 pm", activity: "Revisión del presupuesto trimestral", emoji: "💰" },
      { time: "5:30 pm", activity: "Networking en evento del sector", emoji: "🌐" },
    ],
    universities: ["PUCP", "U. Lima", "UPC", "UP", "ESAN", "USIL"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "En una reunión de estrategia, revisando métricas o cerrando un deal.",
    scene: ["📊", "💼", "🤝", "📈", "🌐"],
    tools: ["Excel", "SAP", "PowerBI", "Salesforce", "Slack"],
  },
  {
    id: "contabilidad",
    title: "Contabilidad",
    area: "Negocios",
    emoji: "🧾",
    color: "#0891b2",
    lightBg: "#ecfeff",
    description:
      "Eres el guardián financiero de las empresas. Registras, analizas y reportas el estado económico real de una organización.",
    salary: "S/. 2,500 – 9,000",
    salaryMin: 2500,
    skills: ["Precisión", "Matemáticas", "Atención al detalle", "Normativa tributaria", "Análisis financiero"],
    dayInLife: [
      { time: "8:00 am", activity: "Registro de operaciones contables del día anterior", emoji: "📒" },
      { time: "9:30 am", activity: "Declaración de impuestos o revisión SUNAT", emoji: "🏛️" },
      { time: "11:00 am", activity: "Conciliación bancaria y estados financieros", emoji: "🏦" },
      { time: "1:00 pm", activity: "Almuerzo y revisión de noticias tributarias", emoji: "🍱" },
      { time: "2:00 pm", activity: "Auditoría interna de comprobantes", emoji: "🔍" },
      { time: "4:00 pm", activity: "Cierre contable mensual", emoji: "📊" },
      { time: "5:30 pm", activity: "Informe a gerencia sobre situación fiscal", emoji: "📑" },
    ],
    universities: ["PUCP", "UNMSM", "UPC", "USMP", "U. Continental", "UCV"],
    outlook: "Estable",
    duration: "5 años",
    nowDoing: "Analizando estados financieros o preparando declaraciones tributarias.",
    scene: ["🧾", "💰", "📊", "🏦", "🔢"],
    tools: ["CONCAR", "Excel", "SIRE SUNAT", "SAP", "PDT"],
  },
  {
    id: "ingenieria-civil",
    title: "Ingeniería Civil",
    area: "Ingeniería",
    emoji: "🏗️",
    color: "#dc2626",
    lightBg: "#fff1f1",
    description:
      "Construyes la infraestructura que sostiene al país: carreteras, puentes, edificios, represas. Tu trabajo dura generaciones.",
    salary: "S/. 4,000 – 14,000",
    salaryMin: 4000,
    skills: ["Matemáticas", "Física", "Gestión de proyectos", "AutoCAD", "Liderazgo de obras"],
    dayInLife: [
      { time: "7:00 am", activity: "Supervisión en obra — revisas avances del día", emoji: "👷" },
      { time: "9:00 am", activity: "Reunión con residente y maestros de obra", emoji: "🤝" },
      { time: "10:30 am", activity: "Diseño y revisión de planos en oficina técnica", emoji: "📐" },
      { time: "1:00 pm", activity: "Almuerzo en obra o en oficina", emoji: "🍱" },
      { time: "2:00 pm", activity: "Control de calidad de materiales", emoji: "🔩" },
      { time: "3:30 pm", activity: "Cálculo estructural con software", emoji: "🖥️" },
      { time: "5:00 pm", activity: "Informe de avance y reporte a cliente", emoji: "📋" },
    ],
    universities: ["UNI", "PUCP", "UNMSM", "UPC", "U. Piura", "UNSA"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "En obra supervisando o en la oficina calculando estructuras.",
    scene: ["🏗️", "👷", "📐", "🔩", "🏛️"],
    tools: ["AutoCAD", "ETABS", "SAP2000", "Revit", "S10"],
  },
  {
    id: "arquitectura",
    title: "Arquitectura",
    area: "Diseño",
    emoji: "🏛️",
    color: "#be185d",
    lightBg: "#fdf2f8",
    description:
      "Diseñas espacios que mejoran la vida de las personas. Combinas arte, ciencia y funcionalidad para crear desde una casa hasta una ciudad.",
    salary: "S/. 3,000 – 10,000",
    salaryMin: 3000,
    skills: ["Creatividad", "Visión espacial", "AutoCAD", "Gestión de proyectos", "Dibujo técnico"],
    dayInLife: [
      { time: "9:00 am", activity: "Revisas referencias e inspiración para proyecto", emoji: "🖼️" },
      { time: "10:00 am", activity: "Dibujas bocetos y esquemas de distribución", emoji: "✏️" },
      { time: "12:00 pm", activity: "Presentación de anteproyecto a cliente", emoji: "🗣️" },
      { time: "1:00 pm", activity: "Almuerzo y recorrido por referencias urbanas", emoji: "🏙️" },
      { time: "2:30 pm", activity: "Modelado 3D del proyecto en Revit o SketchUp", emoji: "🖥️" },
      { time: "4:30 pm", activity: "Coordinación con ingenieros estructurales", emoji: "🤝" },
      { time: "6:00 pm", activity: "Renderizas imágenes del proyecto finalizado", emoji: "✨" },
    ],
    universities: ["PUCP", "UNI", "U. Lima", "UPC", "Ricardo Palma", "USIL"],
    outlook: "Media",
    duration: "5-6 años",
    nowDoing: "Diseñando planos o modelando en 3D con música de fondo.",
    scene: ["🏛️", "✏️", "📐", "🖥️", "🏙️"],
    tools: ["AutoCAD", "Revit", "SketchUp", "Lumion", "Photoshop"],
  },
  {
    id: "psicologia",
    title: "Psicología",
    area: "Salud",
    emoji: "🧠",
    color: "#7c3aed",
    lightBg: "#f5f3ff",
    description:
      "Entiendes el comportamiento humano desde adentro. Ayudas a personas, empresas y comunidades a funcionar mejor emocionalmente.",
    salary: "S/. 2,500 – 8,000",
    salaryMin: 2500,
    skills: ["Empatía", "Escucha activa", "Observación", "Comunicación", "Neutralidad emocional"],
    dayInLife: [
      { time: "9:00 am", activity: "Revisas notas de sesiones anteriores", emoji: "📓" },
      { time: "9:30 am", activity: "Sesión de terapia individual (50 min)", emoji: "💬" },
      { time: "11:00 am", activity: "Segunda sesión con paciente adolescente", emoji: "🧑" },
      { time: "1:00 pm", activity: "Almuerzo y supervisión con colega", emoji: "🍱" },
      { time: "2:30 pm", activity: "Sesión de terapia de pareja", emoji: "👫" },
      { time: "4:00 pm", activity: "Redacción de informes psicológicos", emoji: "📝" },
      { time: "5:30 pm", activity: "Actualización en nuevas técnicas terapéuticas", emoji: "📚" },
    ],
    universities: ["PUCP", "UNMSM", "U. Lima", "UPC", "USMP", "UNFV"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "En una sesión de terapia o redactando informes psicológicos.",
    scene: ["🧠", "💬", "🛋️", "📓", "🌱"],
    tools: ["DSM-5", "Tests psicométricos", "Plataformas de teleconsulta"],
  },
  {
    id: "marketing",
    title: "Marketing & Comunicación",
    area: "Negocios",
    emoji: "📣",
    color: "#ea580c",
    lightBg: "#fff7ed",
    description:
      "Conectas marcas con personas. Diseñas estrategias, creas contenido y usas datos para que los productos lleguen al corazón del consumidor.",
    salary: "S/. 2,500 – 10,000",
    salaryMin: 2500,
    skills: ["Creatividad", "Análisis de datos", "Storytelling", "Social media", "Visión de tendencias"],
    dayInLife: [
      { time: "9:00 am", activity: "Revisas métricas de campañas activas", emoji: "📊" },
      { time: "9:30 am", activity: "Brainstorming de ideas para nuevo lanzamiento", emoji: "💡" },
      { time: "11:00 am", activity: "Aprobación de piezas creativas con el equipo", emoji: "🎨" },
      { time: "1:00 pm", activity: "Almuerzo revisando tendencias en TikTok", emoji: "📱" },
      { time: "2:30 pm", activity: "Reunión con influencers o agencia creativa", emoji: "🤝" },
      { time: "4:00 pm", activity: "Análisis de resultados de campaña Google Ads", emoji: "📈" },
      { time: "5:30 pm", activity: "Presentación de estrategia mensual", emoji: "🎯" },
    ],
    universities: ["U. Lima", "PUCP", "UPC", "USIL", "UP", "ESAN"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "Revisando métricas de campañas o creando contenido para redes sociales.",
    scene: ["📣", "📊", "📱", "🎨", "🎯"],
    tools: ["Meta Ads", "Google Analytics", "Canva", "HubSpot", "Notion"],
  },
  {
    id: "diseno-ux",
    title: "Diseño UX/UI",
    area: "Diseño",
    emoji: "🎨",
    color: "#db2777",
    lightBg: "#fdf2f8",
    description:
      "Haces que la tecnología sea intuitiva y bella. Diseñas la experiencia que millones de personas tienen al usar apps y plataformas digitales.",
    salary: "S/. 3,000 – 10,000",
    salaryMin: 3000,
    skills: ["Creatividad", "Empatía con el usuario", "Figma", "Pensamiento de diseño", "Prototipado"],
    dayInLife: [
      { time: "9:00 am", activity: "Revisas feedback de usuarios de la semana", emoji: "💬" },
      { time: "9:30 am", activity: "Sesión de diseño en Figma — wireframes", emoji: "🖌️" },
      { time: "11:30 am", activity: "User testing con 3 personas reales", emoji: "👥" },
      { time: "1:00 pm", activity: "Almuerzo y revisas Dribbble para inspiración", emoji: "🍱" },
      { time: "2:30 pm", activity: "Refinamiento del design system", emoji: "✨" },
      { time: "4:00 pm", activity: "Handoff a desarrolladores con especificaciones", emoji: "🤝" },
      { time: "5:30 pm", activity: "Revisión de prototipo interactivo", emoji: "📱" },
    ],
    universities: ["PUCP", "UPC", "ISIL", "Toulouse Lautrec", "U. Lima", "UTEC"],
    outlook: "Alta",
    duration: "4-5 años",
    nowDoing: "Diseñando interfaces en Figma o haciendo pruebas con usuarios reales.",
    scene: ["🎨", "🖌️", "📱", "💻", "✨"],
    tools: ["Figma", "Adobe XD", "Illustrator", "Maze", "Notion"],
  },
  {
    id: "enfermeria",
    title: "Enfermería",
    area: "Salud",
    emoji: "💉",
    color: "#0891b2",
    lightBg: "#ecfeff",
    description:
      "Cuidas a las personas en sus momentos más delicados. Eres el contacto humano más constante en cualquier sistema de salud.",
    salary: "S/. 2,500 – 7,000",
    salaryMin: 2500,
    skills: ["Empatía", "Precisión", "Trabajo bajo presión", "Técnicas clínicas", "Comunicación"],
    dayInLife: [
      { time: "7:00 am", activity: "Recepción de turno y revisión de pacientes", emoji: "📋" },
      { time: "8:00 am", activity: "Administración de medicamentos", emoji: "💊" },
      { time: "10:00 am", activity: "Toma de signos vitales y registros", emoji: "📊" },
      { time: "1:00 pm", activity: "Almuerzo entre turnos", emoji: "🍱" },
      { time: "2:00 pm", activity: "Curación de heridas y procedimientos", emoji: "🩹" },
      { time: "4:00 pm", activity: "Educación al paciente y familia", emoji: "👨‍👩‍👧" },
      { time: "6:00 pm", activity: "Reporte de turno al equipo médico", emoji: "📝" },
    ],
    universities: ["UNMSM", "UPCH", "PUCP", "URP", "USMP", "U. Continental"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "Atendiendo pacientes en sala o monitoreando signos vitales.",
    scene: ["💉", "🏥", "💊", "🩹", "❤️"],
    tools: ["Monitor de signos vitales", "Glucómetro", "Sistema HIS"],
  },
  {
    id: "ingenieria-industrial",
    title: "Ingeniería Industrial",
    area: "Ingeniería",
    emoji: "⚙️",
    color: "#475569",
    lightBg: "#f8fafc",
    description:
      "Optimizas sistemas de producción, cadenas de suministro y procesos empresariales. Haces que las cosas funcionen mejor, más rápido y más barato.",
    salary: "S/. 3,500 – 12,000",
    salaryMin: 3500,
    skills: ["Análisis de procesos", "Estadística", "Liderazgo", "Calidad", "Logística"],
    dayInLife: [
      { time: "8:00 am", activity: "Revisión de indicadores de producción", emoji: "📊" },
      { time: "9:00 am", activity: "Recorrido por planta para identificar cuellos de botella", emoji: "🏭" },
      { time: "10:30 am", activity: "Análisis de datos y propuesta de mejora", emoji: "📈" },
      { time: "1:00 pm", activity: "Almuerzo y revisión de proveedores", emoji: "🍱" },
      { time: "2:00 pm", activity: "Implementación de metodología Lean", emoji: "⚙️" },
      { time: "4:00 pm", activity: "Reunión con gerencia de operaciones", emoji: "🤝" },
      { time: "5:30 pm", activity: "Informe de eficiencia semanal", emoji: "📋" },
    ],
    universities: ["UNI", "PUCP", "U. Lima", "UPC", "UNMSM", "U. Piura"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "Analizando procesos productivos o implementando mejoras en planta.",
    scene: ["⚙️", "🏭", "📊", "📈", "🔧"],
    tools: ["Minitab", "AutoCAD", "SAP", "Excel avanzado", "Arena Simulation"],
  },
  {
    id: "economia",
    title: "Economía",
    area: "Negocios",
    emoji: "💹",
    color: "#16a34a",
    lightBg: "#f0fdf4",
    description:
      "Analizas cómo funciona el sistema económico a nivel macro y micro. Informas decisiones de gobierno, banca central, empresas y organismos internacionales.",
    salary: "S/. 3,500 – 14,000",
    salaryMin: 3500,
    skills: ["Estadística", "Econometría", "Análisis de datos", "Pensamiento crítico", "Programación (R/Python)"],
    dayInLife: [
      { time: "9:00 am", activity: "Revisas reportes del BCRP e INEI", emoji: "📰" },
      { time: "10:00 am", activity: "Modelado econométrico con datos de mercado", emoji: "📊" },
      { time: "12:00 pm", activity: "Reunión con equipo de research", emoji: "🤝" },
      { time: "1:00 pm", activity: "Almuerzo y revisión de noticias económicas", emoji: "🍱" },
      { time: "2:30 pm", activity: "Redacción de informe de coyuntura económica", emoji: "✍️" },
      { time: "4:00 pm", activity: "Presentación de análisis a directivos", emoji: "📈" },
      { time: "5:30 pm", activity: "Actualización de modelos de proyección", emoji: "💹" },
    ],
    universities: ["PUCP", "U. Lima", "UNMSM", "UP", "ESAN", "UPC"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "Modelando proyecciones económicas o redactando un informe de coyuntura.",
    scene: ["💹", "📊", "📈", "🏦", "🌍"],
    tools: ["Stata", "R", "Python", "Bloomberg", "EViews"],
  },
  {
    id: "gastronomia",
    title: "Gastronomía",
    area: "Gastronomía",
    emoji: "👨‍🍳",
    color: "#dc2626",
    lightBg: "#fff1f1",
    description:
      "Llevas la cocina peruana al mundo. Creas experiencias culinarias únicas que combinan técnica, creatividad y cultura. Perú es el país de la gastronomía latinoamericana.",
    salary: "S/. 2,000 – 10,000",
    salaryMin: 2000,
    skills: ["Creatividad", "Paladar desarrollado", "Resistencia física", "Gestión de cocina", "Pasión"],
    dayInLife: [
      { time: "8:00 am", activity: "Revisas mise en place y lista de insumos", emoji: "📋" },
      { time: "9:00 am", activity: "Preparación de fondos, salsas y bases", emoji: "🍲" },
      { time: "11:00 am", activity: "Degustación y ajuste de nuevos platos", emoji: "🍽️" },
      { time: "12:00 pm", activity: "Coordinación con brigada para el servicio", emoji: "👨‍🍳" },
      { time: "1:00 pm", activity: "Servicio del almuerzo — cocina a full velocidad", emoji: "🔥" },
      { time: "3:00 pm", activity: "Limpieza y preparación para servicio de noche", emoji: "🧹" },
      { time: "6:00 pm", activity: "Servicio de cena — tu mejor momento del día", emoji: "✨" },
    ],
    universities: ["Le Cordon Bleu", "USIL", "ISG", "D'Gallia", "UTP", "UNMSM"],
    outlook: "Alta",
    duration: "3-5 años",
    nowDoing: "En cocina preparando mise en place o creando un nuevo plato.",
    scene: ["👨‍🍳", "🍳", "🌶️", "🐟", "✨"],
    tools: ["Thermomix", "Sous vide", "Pacojet", "Cuchillos japoneses"],
  },
  {
    id: "periodismo",
    title: "Periodismo & Comunicación",
    area: "Humanidades",
    emoji: "📰",
    color: "#1d4ed8",
    lightBg: "#eff6ff",
    description:
      "Informas, investigas y haces que la sociedad rinda cuentas. El periodismo es el cuarto poder — esencial para cualquier democracia.",
    salary: "S/. 2,000 – 8,000",
    salaryMin: 2000,
    skills: ["Escritura", "Investigación", "Entrevistas", "Edición de video", "Redes sociales"],
    dayInLife: [
      { time: "8:00 am", activity: "Revisas agenda de noticias y conferencias", emoji: "📰" },
      { time: "9:00 am", activity: "Reportería — entrevistas en campo", emoji: "🎤" },
      { time: "11:00 am", activity: "Redacción de nota o crónica del día", emoji: "✍️" },
      { time: "1:00 pm", activity: "Almuerzo y monitoreo de redes", emoji: "📱" },
      { time: "2:30 pm", activity: "Edición de video o audio para multiplataforma", emoji: "🎬" },
      { time: "4:00 pm", activity: "Publicación y seguimiento en tiempo real", emoji: "🚀" },
      { time: "6:00 pm", activity: "Cobertura de evento de última hora", emoji: "🔴" },
    ],
    universities: ["PUCP", "U. Lima", "UNMSM", "UPC", "UP", "USMP"],
    outlook: "Media",
    duration: "5 años",
    nowDoing: "En campo haciendo reportería o redactando una nota para su medio.",
    scene: ["📰", "🎤", "📡", "✍️", "📸"],
    tools: ["Adobe Premiere", "Audacity", "WordPress", "Redes sociales"],
  },
  {
    id: "ingenieria-minas",
    title: "Ingeniería de Minas",
    area: "Ingeniería",
    emoji: "⛏️",
    color: "#92400e",
    lightBg: "#fffbeb",
    description:
      "Extraes los minerales que hacen posible la tecnología moderna. Perú es uno de los mayores productores de cobre, oro y zinc del mundo.",
    salary: "S/. 5,000 – 18,000",
    salaryMin: 5000,
    skills: ["Geología", "Explosivos", "Seguridad minera", "Gestión ambiental", "Liderazgo"],
    dayInLife: [
      { time: "6:00 am", activity: "Briefing de seguridad antes de bajar a mina", emoji: "⛑️" },
      { time: "7:00 am", activity: "Supervisión de tajo abierto o galería", emoji: "⛏️" },
      { time: "9:00 am", activity: "Control de perforación y voladura", emoji: "💥" },
      { time: "12:00 pm", activity: "Almuerzo en campamento minero", emoji: "🍽️" },
      { time: "1:30 pm", activity: "Análisis geológico y planeamiento de avance", emoji: "🗺️" },
      { time: "3:00 pm", activity: "Reunión de seguridad y reporte de incidentes", emoji: "📋" },
      { time: "5:00 pm", activity: "Cierre de guardia y relevo de turno", emoji: "🔄" },
    ],
    universities: ["UNI", "UNMSM", "U. Nacional de Ingeniería", "UNSA", "UNDAC", "U. Continental"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "Supervisando operaciones en tajo o analizando muestras geológicas.",
    scene: ["⛏️", "⛰️", "💎", "⛑️", "🗺️"],
    tools: ["Vulcan", "Surpac", "AutoCAD", "GPS minero"],
  },
  {
    id: "odontologia",
    title: "Odontología",
    area: "Salud",
    emoji: "🦷",
    color: "#0284c7",
    lightBg: "#f0f9ff",
    description:
      "Cuidas la salud bucal de las personas. Más que dientes, trabajas con la confianza y autoestima de tus pacientes.",
    salary: "S/. 3,000 – 12,000",
    salaryMin: 3000,
    skills: ["Precisión manual", "Empatía", "Anatomía", "Técnica clínica", "Paciencia"],
    dayInLife: [
      { time: "9:00 am", activity: "Revisas agenda de pacientes del día", emoji: "📅" },
      { time: "9:30 am", activity: "Primera consulta — diagnóstico y plan de tratamiento", emoji: "🔍" },
      { time: "11:00 am", activity: "Procedimiento de endodoncia o extracción", emoji: "🦷" },
      { time: "1:00 pm", activity: "Almuerzo y descanso entre turnos", emoji: "🍱" },
      { time: "2:00 pm", activity: "Sesión de ortodoncia — ajuste de brackets", emoji: "✨" },
      { time: "3:30 pm", activity: "Colocación de carillas o blanqueamiento", emoji: "😁" },
      { time: "5:00 pm", activity: "Revisión de resultados de radiografías", emoji: "🩻" },
    ],
    universities: ["UNMSM", "UPCH", "PUCP", "UPC", "U. Continental", "USMP"],
    outlook: "Alta",
    duration: "6 años",
    nowDoing: "Atendiendo pacientes en tu consultorio o realizando un procedimiento dental.",
    scene: ["🦷", "😁", "🔬", "💉", "✨"],
    tools: ["Rx periapical", "Scanner intraoral", "Ultrasonido dental"],
  },
  {
    id: "ingenieria-ambiental",
    title: "Ingeniería Ambiental",
    area: "Ingeniería",
    emoji: "🌿",
    color: "#16a34a",
    lightBg: "#f0fdf4",
    description:
      "Proteges el planeta mientras las empresas crecen. Diseñas soluciones para reducir el impacto ambiental de industrias, ciudades y proyectos.",
    salary: "S/. 3,000 – 10,000",
    salaryMin: 3000,
    skills: ["Química", "Biología", "Legislación ambiental", "SIG", "Gestión de residuos"],
    dayInLife: [
      { time: "8:00 am", activity: "Monitoreo de calidad de aire y agua", emoji: "🌊" },
      { time: "9:30 am", activity: "Elaboración de Estudio de Impacto Ambiental", emoji: "📝" },
      { time: "11:00 am", activity: "Visita a planta para auditoría ambiental", emoji: "🏭" },
      { time: "1:00 pm", activity: "Almuerzo al aire libre — parte del trabajo", emoji: "🌳" },
      { time: "2:30 pm", activity: "Análisis de muestras en laboratorio", emoji: "🔬" },
      { time: "4:00 pm", activity: "Presentación de resultados a empresa cliente", emoji: "📊" },
      { time: "5:30 pm", activity: "Actualización de registros OEFA/OSINERGMIN", emoji: "📋" },
    ],
    universities: ["UNI", "PUCP", "UNMSM", "U. Agraria La Molina", "UNSA", "UCV"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "Realizando monitoreos ambientales o elaborando estudios de impacto.",
    scene: ["🌿", "🌊", "♻️", "🌍", "🔬"],
    tools: ["ArcGIS", "AutoCAD", "ENVI", "R", "Equipos de muestreo"],
  },
  {
    id: "educacion",
    title: "Educación & Pedagogía",
    area: "Educación",
    emoji: "📚",
    color: "#7c3aed",
    lightBg: "#f5f3ff",
    description:
      "Formas a las generaciones que cambiarán el país. Los mejores docentes no enseñan asignaturas — enseñan a pensar.",
    salary: "S/. 2,000 – 7,000",
    salaryMin: 2000,
    skills: ["Comunicación", "Empatía", "Didáctica", "Creatividad", "Paciencia"],
    dayInLife: [
      { time: "7:30 am", activity: "Preparas materiales y sesión del día", emoji: "📋" },
      { time: "8:00 am", activity: "Primera clase del día — dinámica de inicio", emoji: "👋" },
      { time: "10:00 am", activity: "Clase con el grupo más desafiante — tu favorito", emoji: "🌟" },
      { time: "12:00 pm", activity: "Almuerzo y revisión de tareas", emoji: "🍱" },
      { time: "1:00 pm", activity: "Tutoría personalizada con alumno que necesita apoyo", emoji: "🤝" },
      { time: "3:00 pm", activity: "Reunión de padres de familia", emoji: "👨‍👩‍👧" },
      { time: "4:30 pm", activity: "Planificación curricular para la semana", emoji: "📅" },
    ],
    universities: ["PUCP", "UNMSM", "UNE La Cantuta", "U. Privada del Norte", "USIL", "UCV"],
    outlook: "Estable",
    duration: "5 años",
    nowDoing: "Preparando una clase o en el aula con sus estudiantes.",
    scene: ["📚", "✏️", "🏫", "🌟", "🤝"],
    tools: ["Google Classroom", "Canva", "Kahoot", "Moodle", "Pizarra digital"],
  },
  {
    id: "nutricion",
    title: "Nutrición & Dietética",
    area: "Salud",
    emoji: "🥗",
    color: "#16a34a",
    lightBg: "#f0fdf4",
    description:
      "Transformas la relación de las personas con su alimentación. Trabajas en hospitales, clínicas, empresas deportivas y consultorios propios.",
    salary: "S/. 2,000 – 7,000",
    salaryMin: 2000,
    skills: ["Bioquímica", "Anatomía", "Empatía", "Elaboración de dietas", "Educación alimentaria"],
    dayInLife: [
      { time: "9:00 am", activity: "Consulta inicial con nuevo paciente — anamnesis", emoji: "📋" },
      { time: "10:00 am", activity: "Análisis de composición corporal", emoji: "⚖️" },
      { time: "11:00 am", activity: "Elaboración de plan nutricional personalizado", emoji: "🥗" },
      { time: "1:00 pm", activity: "Almuerzo saludable — practicas lo que predicas", emoji: "🍎" },
      { time: "2:00 pm", activity: "Seguimiento de paciente crónico", emoji: "📊" },
      { time: "3:30 pm", activity: "Taller de educación alimentaria en empresa", emoji: "👨‍🏫" },
      { time: "5:00 pm", activity: "Actualización de protocolos y literatura científica", emoji: "📚" },
    ],
    universities: ["UNMSM", "UPCH", "UNI", "U. Agraria La Molina", "URP", "USMP"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "Atendiendo consultas o elaborando planes nutricionales personalizados.",
    scene: ["🥗", "🍎", "⚖️", "📊", "💪"],
    tools: ["Software de análisis nutricional", "Báscula de bioimpedancia"],
  },
  {
    id: "turismo",
    title: "Turismo & Hotelería",
    area: "Humanidades",
    emoji: "✈️",
    color: "#0891b2",
    lightBg: "#ecfeff",
    description:
      "Muestras lo mejor del Perú al mundo. Diseñas experiencias de viaje únicas y gestionas destinos turísticos que generan valor para las comunidades.",
    salary: "S/. 2,000 – 8,000",
    salaryMin: 2000,
    skills: ["Idiomas", "Organización", "Servicio al cliente", "Cultura general", "Gestión de crisis"],
    dayInLife: [
      { time: "8:00 am", activity: "Check-in de grupos y coordinación con guías", emoji: "🗺️" },
      { time: "9:30 am", activity: "Tour por Miraflores, Centro Histórico o Cusco", emoji: "🏛️" },
      { time: "12:00 pm", activity: "Almuerzo gastronómico con turistas", emoji: "🍽️" },
      { time: "2:00 pm", activity: "Coordinación logística para el día siguiente", emoji: "📋" },
      { time: "3:30 pm", activity: "Venta de paquetes a nuevos clientes", emoji: "💼" },
      { time: "5:00 pm", activity: "Reporte de operaciones y revisión de reservas", emoji: "📊" },
      { time: "7:00 pm", activity: "Cena de bienvenida con grupo internacional", emoji: "🌍" },
    ],
    universities: ["USIL", "U. San Martín", "U. Le Cordon Bleu", "UPC", "UNMSM", "UP"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "Guiando turistas por Perú o coordinando el siguiente viaje del grupo.",
    scene: ["✈️", "🗺️", "🏛️", "🌍", "📸"],
    tools: ["Amadeus GDS", "Opera PMS", "TripAdvisor", "Booking"],
  },
  {
    id: "relaciones-internacionales",
    title: "Relaciones Internacionales",
    area: "Humanidades",
    emoji: "🌐",
    color: "#1d4ed8",
    lightBg: "#eff6ff",
    description:
      "Navegas el sistema internacional: diplomacia, comercio exterior, organismos multilaterales y política exterior. Representas al país o a organizaciones globales.",
    salary: "S/. 3,000 – 12,000",
    salaryMin: 3000,
    skills: ["Idiomas (mínimo 2)", "Análisis político", "Negociación", "Protocolo", "Geopolítica"],
    dayInLife: [
      { time: "9:00 am", activity: "Revisas cable diplomático y noticias internacionales", emoji: "📰" },
      { time: "10:00 am", activity: "Reunión con delegación extranjera", emoji: "🤝" },
      { time: "12:00 pm", activity: "Almuerzo protocolar con diplomáticos", emoji: "🍽️" },
      { time: "2:00 pm", activity: "Redacción de notas diplomáticas o informes", emoji: "✍️" },
      { time: "4:00 pm", activity: "Seguimiento de negociaciones comerciales bilaterales", emoji: "📋" },
      { time: "5:30 pm", activity: "Evento de la embajada o cónsul", emoji: "🎉" },
      { time: "7:00 pm", activity: "Estudio de idioma o actualización geopolítica", emoji: "📚" },
    ],
    universities: ["PUCP", "UP", "U. Lima", "USMP", "UNMSM", "UPC"],
    outlook: "Media",
    duration: "5 años",
    nowDoing: "En negociaciones internacionales o redactando informes de política exterior.",
    scene: ["🌐", "🤝", "🏛️", "✈️", "📋"],
    tools: ["Idiomas", "Protocolo diplomático", "Derecho Internacional"],
  },
  {
    id: "veterinaria",
    title: "Medicina Veterinaria",
    area: "Salud",
    emoji: "🐾",
    color: "#d97706",
    lightBg: "#fffbeb",
    description:
      "Cuidas la salud animal — desde mascotas hasta ganado y fauna silvestre. En Perú tienes enorme campo en ganadería, acuicultura y conservación.",
    salary: "S/. 2,500 – 8,000",
    salaryMin: 2500,
    skills: ["Empatía animal", "Cirugía", "Diagnóstico clínico", "Resistencia", "Farmacología"],
    dayInLife: [
      { time: "8:00 am", activity: "Atención de urgencias de la mañana", emoji: "🚨" },
      { time: "9:30 am", activity: "Consultas programadas — perros, gatos, exóticos", emoji: "🐕" },
      { time: "11:00 am", activity: "Cirugía de esterilización o procedimiento mayor", emoji: "🏥" },
      { time: "1:00 pm", activity: "Almuerzo con el equipo veterinario", emoji: "🍱" },
      { time: "2:30 pm", activity: "Vacunación y controles de rutina", emoji: "💉" },
      { time: "4:00 pm", activity: "Análisis de resultados de laboratorio", emoji: "🔬" },
      { time: "5:30 pm", activity: "Visita a granja o establo para chequeo de ganado", emoji: "🐄" },
    ],
    universities: ["UNMSM", "UPCH", "U. Cayetano Heredia", "UNA Puno", "UNSA", "UCV"],
    outlook: "Alta",
    duration: "5-6 años",
    nowDoing: "Atendiendo consultas o en quirófano realizando una cirugía.",
    scene: ["🐾", "🐕", "🏥", "💉", "🔬"],
    tools: ["Ecógrafo portátil", "Rx digital", "Laboratorio clínico"],
  },
];
