import type { Career, CareerCosmetic } from "@/types/avatar";

export const CAREER_COSMETICS: Record<string, CareerCosmetic> = {
  software: {
    career: "software",
    label: "Ingeniería de Software",
    accessory: "laptop",
    accessoryColor: "#185FA5",
    hat: "none",
    badge: "</> ",
    background: "abstract",
    accentColor: "#378ADD",
    description: "Laptop y código",
  },
  medicina: {
    career: "medicina",
    label: "Medicina",
    accessory: "stethoscope",
    accessoryColor: "#185FA5",
    hat: "surgical-cap",
    badge: "⚕",
    background: "lab",
    accentColor: "#378ADD",
    description: "Estetoscopio y gorra quirúrgica",
  },
  ingenieria: {
    career: "ingenieria",
    label: "Ingeniería",
    accessory: "wrench",
    accessoryColor: "#3B6D11",
    hat: "hard-hat",
    badge: "⚙",
    background: "city",
    accentColor: "#639922",
    description: "Casco de seguridad y llave inglesa",
  },
  matematicas: {
    career: "matematicas",
    label: "Matemáticas",
    accessory: "compass",
    accessoryColor: "#533AB7",
    hat: "mortarboard",
    badge: "∑",
    background: "library",
    accentColor: "#7F77DD",
    description: "Birrete y compás geométrico",
  },
  diseno: {
    career: "diseno",
    label: "Diseño",
    accessory: "palette",
    accessoryColor: "#D4537E",
    hat: "beret",
    badge: "✦",
    background: "abstract",
    accentColor: "#ED93B1",
    description: "Boina artística y paleta de colores",
  },
  literatura: {
    career: "literatura",
    label: "Literatura",
    accessory: "quill",
    accessoryColor: "#854F0B",
    hat: "reading-glasses",
    badge: "✍",
    background: "library",
    accentColor: "#EF9F27",
    description: "Pluma de escribir y gafas de lectura",
  },
  musica: {
    career: "musica",
    label: "Música",
    accessory: "music-note",
    accessoryColor: "#993556",
    hat: "headphones",
    badge: "♪",
    background: "abstract",
    accentColor: "#D4537E",
    description: "Auriculares y nota musical",
  },
  administracion: {
    career: "administracion",
    label: "Administración",
    accessory: "briefcase",
    accessoryColor: "#185FA5",
    hat: "tie",
    badge: "◈",
    background: "city",
    accentColor: "#378ADD",
    description: "Corbata ejecutiva y maletín",
  },
  psicologia: {
    career: "psicologia",
    label: "Psicología",
    accessory: "brain",
    accessoryColor: "#533AB7",
    hat: "none",
    badge: "Ψ",
    background: "nature",
    accentColor: "#7F77DD",
    description: "Símbolo psi y libro de apuntes",
  },
  derecho: {
    career: "derecho",
    label: "Derecho",
    accessory: "scales",
    accessoryColor: "#854F0B",
    hat: "lawyer-wig",
    badge: "⚖",
    background: "library",
    accentColor: "#EF9F27",
    description: "Peluca de abogado y balanza de justicia",
  },
  arquitectura: {
    career: "arquitectura",
    label: "Arquitectura",
    accessory: "ruler",
    accessoryColor: "#3B6D11",
    hat: "beret",
    badge: "⌂",
    background: "city",
    accentColor: "#97C459",
    description: "Boina y escuadra de arquitecto",
  },
  astronauta: {
    career: "astronauta",
    label: "Astronáutica",
    accessory: "rocket",
    accessoryColor: "#185FA5",
    hat: "helmet",
    badge: "★",
    background: "sky",
    accentColor: "#378ADD",
    description: "Casco espacial y cohete",
  },
  gastronomia: {
    career: "gastronomia",
    label: "Gastronomía",
    accessory: "chef-knife",
    accessoryColor: "#D85A30",
    hat: "chef-hat",
    badge: "♨",
    background: "nature",
    accentColor: "#F0997B",
    description: "Gorro de chef y cuchillo",
  },
  marketing: {
    career: "marketing",
    label: "Marketing",
    accessory: "megaphone",
    accessoryColor: "#993556",
    hat: "none",
    badge: "◉",
    background: "abstract",
    accentColor: "#D4537E",
    description: "Megáfono y estrategia",
  },
};

export const SKIN_TONES: Record<string, { fill: string; shadow: string; label: string }> = {
  light:          { fill: "#FDDBB4", shadow: "#F0B97D", label: "Clara" },
  "medium-light": { fill: "#F5C18A", shadow: "#D99A5E", label: "Medio clara" },
  medium:         { fill: "#D4956A", shadow: "#B3744D", label: "Media" },
  "medium-dark":  { fill: "#A0623A", shadow: "#7D4928", label: "Medio oscura" },
  dark:           { fill: "#5C3317", shadow: "#3D2010", label: "Oscura" },
};

export const HAIR_COLORS: Record<string, { fill: string; label: string }> = {
  black:  { fill: "#1A1A1A", label: "Negro" },
  brown:  { fill: "#5C3317", label: "Castaño" },
  blonde: { fill: "#E8C97A", label: "Rubio" },
  red:    { fill: "#C0392B", label: "Rojo" },
  gray:   { fill: "#888780", label: "Gris" },
  white:  { fill: "#F1EFE8", label: "Blanco" },
};

export const EYE_COLORS: Record<string, { fill: string; label: string }> = {
  brown:  { fill: "#5C3317", label: "Café" },
  hazel:  { fill: "#7D6A2A", label: "Avellana" },
  green:  { fill: "#2E7D32", label: "Verde" },
  blue:   { fill: "#1565C0", label: "Azul" },
  gray:   { fill: "#607D8B", label: "Gris" },
};
export { Career };

